version: "3"

services:
        web:
                image: nginx
                ports:
                  - "80:80"
                  - "8081:8081"
                volumes:
#                  - ./web:/usr/share/nginx/html
                  - ./web:/var/www/html
                  - ./nginx_conf:/etc/nginx/conf.d

        prometheus:
                image: prom/prometheus
                ports: ["9090:9090"]
                volumes:
                  - ./prometheus:/etc/prometheus/

        nginx_exporter:
                image: nginx/nginx-prometheus-exporter:0.1.0
#                network_mode: "host"
                restart: always
                command:
                  - -nginx.scrape-uri
                  - http://51.250.18.162/nginx_status
                ports:
                  - "9113:9113"

        grafana:
                image: grafana/grafana-enterprise:8.2.0
                ports:
                  - "3000:3000"
                environment:
                  - GF_SECURITY_ADMIN_PASSWORD=Qwerty123
                volumes:
                  - ./grafana/provisioning:/etc/grafana/provisioning
#                  - ./grafana/dashboards:/etc/grafana/dashboards
#                  - ./grafana-data:/var/lib/grafana
