version: "3"

services:
        web:
                build: web/
                ports: ["80:80"]
        grafana:
                build: grafana/
                ports: ["3000:3000"]
        prometeus:
                build: prometheus/
                ports: ["9090:9090"]
