global:
  scrape_interval: 15s
scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'my_host'
    scrape_interval: 5s
    static_configs:
      - targets: ['51.250.18.162:9100']

  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['51.250.18.162:9113']
