name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.31.114
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
#          script: |
#            whoami
#            sudo mkdir /var/test
          local: web
          remote: var/test
#          run: sudo git clone https://github.com/Criogen11/test_sre.git
