name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        uses: actions/checkout@v2
      - run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      
      
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.31.114
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            sudo mkdir /test_sre
            sudo chown -R admin:admin /test_sre

      
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 51.250.31.114
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
          source: "deploy.tar"
          target: "/test_sre"


      - name: unzip tar
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.31.114
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            cd /var/test
            tar -xvf deploy.tar
            sed -i 's/orgId: 1/orgId: 1\n     url: http://'$ENV_IP':9090/g' /test_sre/deploy/grafana/provisioning/datasources/datasource.yml
            sed -i 's/# targets my_host/# targets my_host\n      -targets: ['$ENV_IP':9100]/g' /test_sre/deploy/prometheus/prometheus.yml
            sed -i 's/# targets nginx/# targets nginx\n      -targets: ['$ENV_IP':9113]/g' /test_sre/deploy/prometheus/prometheus.yml
