name: Deploy

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start deploy  
        uses: appleboy/telegram-action@master
        with:
          to: 273552356
          token: 1716900369:AAGjIaDMcM1rGR58PyMsZI11fDIkY3JYUOI
          message: |
            ${{ github.actor }} :
            Commit message: Start deploy, launch in 5 minutes  
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      
      - name: Run a multi-line script
        uses: actions/checkout@v2
      - run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      
      
      - name: add folper and repo docker and install docker
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.23.83
          username: admin
          key: ${{ secrets.KEY1 }}
          port: 22
          script: |
            whoami
            sudo mkdir /var/test_sre
            sudo chown -R admin:admin /var/test_sre
            sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            sudo yum install -y docker-ce docker-ce-cli containerd.io wget

      - name: run docker and get docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.23.83
          username: admin
          key: ${{ secrets.KEY1 }}
          port: 22
          script: |
            whoami
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 51.250.23.83
          username: admin
          key: ${{ secrets.KEY1 }}
          port: 22
          source: "deploy.tar"
          target: "/var/test_sre"


      - name: unzip tar
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.23.83
          username: admin
          key: ${{ secrets.KEY1 }}
          port: 22
          script: |
            whoami
            cd /var/test_sre
            tar -xvf deploy.tar
            sudo chmod +x /usr/local/bin/docker-compose
            
      
      - name: add host ip
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.23.83
          username: admin
          key: ${{ secrets.KEY1 }}
          port: 22
          script: |
            whoami
            sed -i 's/# import url/# import url\n    url: '$ENV_IP':9090/g' /var/test_sre/build/grafana/provisioning/datasources/datasource.yml
            sed -i 's/# targets my_host/# targets my_host\n      - targets: ['$ENV_IP':9100]/g' /var/test_sre/build/prometheus/prometheus.yml
            sed -i 's/# targets nginx/# targets nginx\n      - targets: ['$ENV_IP':9113]/g' /var/test_sre/build/prometheus/prometheus.yml
            cd /var/test_sre/build/
            wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O /var/test_sre/build/grafana/ssl/root.crt
            sudo chmod 0760 /var/test_sre/build/grafana/ssl/root.crt
            sudo chmod +rx /var/test_sre/build/grafana/ssl/root.crt
            sudo chmod 666 /var/run/docker.sock
            docker-compose build
            docker-compose up -d
            
      - name: Finish
        uses: appleboy/telegram-action@master
        with:
          to: 273552356
          token: 1716900369:AAGjIaDMcM1rGR58PyMsZI11fDIkY3JYUOI
          message: |
            ${{ github.actor }} :
            Commit message: ${{ job.status }}
            
