name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.31.114
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            sudo mkdir /var/test
            sudo chown -R admin:admin /var/test
#          source: web
#          target: var/test
#          run: sudo git clone https://github.com/Criogen11/test_sre.git
#          run: cd web && rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . admin@51.250.31.114:/var/tes
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
#        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          host: 51.250.31.114
          username: admin
#          privateKey: ${{ secrets.KEY }}
          key: ${{ secrets.KEY }}
          port: 22
#          local: var/test/
#          remote: web/
          source: "."
          target: "var/test/"

