name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.31.114
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            sudo mkdir /var/test
          run: cd web && rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . sudo admin@51.250.31.114:/var/test
